# Generated by Django 5.0.6 on 2024-05-28 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_shedule', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='day_of_week',
            field=models.DateField(max_length=20),
        ),
    ]
